services:
  # Backend Service
  - type: web
    name: todo-backend
    env: docker
    dockerfilePath: ./Dockerfile.backend.render
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: todo-postgres
          property: connectionString
    healthCheckPath: /health

  # Frontend Service  
  - type: web
    name: todo-frontend
    env: docker
    dockerfilePath: ./Dockerfile.frontend.render
    envVars:
      - key: VITE_API_URL
        value: https://todo-backend.onrender.com/api

# Database
databases:
  - name: todo-postgres
    databaseName: todoapp
    user: postgres
